"""Single-feature separability probe — the honesty check on every injector.

The question this answers
-------------------------
"Is this attack a cartoon?" A synthetic attack is worthless if one column gives
it away, because a detector trained on it learns that column and nothing else,
posts a 0.99 AUC, and collapses the moment it meets traffic that was not
generated by us. So after every injector is written, we fit a **depth-1 decision
stump on every single feature** against that injector's label, and require the
best one to stay under :data:`GATE_AUC`.

That number goes in the injector's docstring. It is the sentence we can say to a
judge: *no single column separates this attack from legitimate traffic; the
detector has to combine evidence.*

How the probe is deliberately adversarial
-----------------------------------------
* It reports the **stronger** of two measures per feature: the gini-optimal
  depth-1 stump, and the column's own rank AUC (``max(a, 1 - a)``). A stump
  optimises gini, not AUC, so a column can separate better than its stump does.
  Taking the max means we cannot flatter ourselves by accident.
* Because it takes ``max(a, 1 - a)``, the magnitude alone is **direction-blind**,
  and that is actively dangerous: ``auth_response=approved`` at 0.69 reads as
  "this attack is approved more often" when the truth is the exact opposite, and
  card testing's canonical signature is an *elevated decline ratio*. So every
  row also carries ``direction`` — ``hi`` when the attack sits high on the
  feature, ``lo`` when it sits low — and the table prints it. A reviewer who
  reads only the magnitude can get the sign of a feature backwards; a Day 4
  model trained on a misread table would learn card testing inverted.
* Categorical columns are exploded to **one indicator per level**, so
  "``mcc`` is 6012" is probed on its own rather than hidden inside a nominal
  column a tree cannot split sensibly.
* Null patterns are probed explicitly. If an attack were, say, entirely on the
  agentic rail, ``ag_agent_id_isnull`` would find it immediately.
* List-valued columns are probed by length, and the mandate by its age.

What is excluded, and why that is not cheating
----------------------------------------------
Free-form identifiers — ``event_id``, ``customer_id``, ``merchant_id``,
``device_id``, ``ip``, ``terminal_id``, agent and mandate ids — are excluded.
They have thousands of levels, and a stump on a target-encoded identifier is
memorising which entities the campaign touched, not measuring whether the attack
is subtle. Their *aggregate* behaviour (velocity within a BIN, merchant fan-out,
device reuse across customers) is precisely what the firewall is supposed to
use, and those are multi-row features that a single-column probe cannot express
by construction. Excluding the raw ids makes this probe harder to pass, not
easier: it removes the shortcut and leaves only the columns an attack could
plausibly betray itself on.

Label columns are excluded for the obvious reason (HARD RULE 1). So are the two
post-hoc dispute columns: they resolve weeks after the authorisation, so a
detector that used them would be reading the future, and a probe that measured
them would be reporting a number no deployed model could reproduce.

Why there is a second AUC column, and which one the gate uses
--------------------------------------------------------------
Some properties of an attack are its **definition**, not evidence of it. Every
F1 attack carries an agentic block and only ~15% of the background does, so any
F1 injector scores ~0.92 on the nullity of any ``ag_`` column before it does
anything. F1-03 is a refund attack and refunds are ~2% of traffic, so
``txn_type=refund`` alone scores ~0.99. Neither number means the attack is easy
to catch; both mean it happens where we already said it happens.

So an injector may declare a **definitional slice** of the background it should
be measured inside — :meth:`BaseAttack.probe_slice` — and this module reports
``slice_auc`` alongside ``best_auc``. **The gate applies to ``slice_auc``
whenever a slice is declared**, because "among refunds by agent-mediated
customers, does one column give this away?" is the question an issuer actually
faces. The unconditional number stays in the table so the denominator change is
visible rather than quiet.

This is the same reasoning the Day 1 audit reached about the rail (CLAUDE.md:
"rail identity is unhideable, and that is fine"), applied consistently and
declared per injector rather than special-cased here.
"""

from __future__ import annotations

from typing import Final

import numpy as np
import pandas as pd

from mantis.core.events import LABEL_COLUMNS, POST_HOC_COLUMNS

__all__ = [
    "EXCLUDED_COLUMNS",
    "GATE_AUC",
    "SLICE_ALLOWED_COLUMNS",
    "THIN_SLICE_ROWS",
    "build_probe_matrix",
    "build_slices",
    "format_probe_table",
    "probe_attack",
    "probe_report",
]

#: The bar an injector has to clear. Above this, the attack announces itself on
#: one column and is not worth generating.
GATE_AUC: Final[float] = 0.95

#: Below this many background rows, a conditional AUC is flagged as thin. Not an
#: error -- a genuinely rare slice is still the right denominator -- but a number
#: measured against a few hundred rows must not be quoted as if it were measured
#: against sixty thousand.
THIN_SLICE_ROWS: Final[int] = 750

#: The **only** columns a ``probe_slice`` may condition on.
#:
#: A slice narrows the population an attack is graded against, so an injector
#: choosing its own slice is marking its own homework unless the choice is
#: constrained. The rule that makes it legitimate: *a slice may condition only
#: on facts a detector already knows before it scores, and which are not
#: consequences of the attack.*
#:
#: Rail and processing code qualify -- a deployed detector genuinely does branch
#: on "is this an agent-mediated authorisation" and "is this a credit going
#: out", and grading an agentic attack against card-present traffic measures the
#: rail rather than the attack. Everything else does not. Slicing F1-01 to
#: "agentic" is fair; slicing it to "agentic and provenance chain longer than
#: three" would be conditioning on the attack's own footprint, and the AUC that
#: came back would be meaningless.
#:
#: Deliberately absent, and worth naming: ``amount`` (an attack chooses it),
#: ``auth_response`` and ``settled`` (the issuer's decision on *this* message,
#: unknown at scoring time), every ``ag_scope_*``, ``ag_mandate_*`` and
#: behavioural ``ag_*`` column (all attack footprint), and the label and
#: post-hoc columns.
SLICE_ALLOWED_COLUMNS: Final[frozenset[str]] = frozenset(
    {
        "channel",
        "entry_mode",
        "txn_type",
        "mcc",
        "currency",
        "merchant_country",
        # Read for its nullity only: "does this authorisation carry an agentic
        # block at all". That is rail identity, which Day 1 settled is
        # unhideable and definitional.
        "ag_agent_id",
    }
)

#: Identifier columns, excluded with reasons. See the module docstring.
EXCLUDED_COLUMNS: Final[dict[str, str]] = {
    "event_id": "unique per row; carries no information a detector could use",
    "customer_id": "identifier with thousands of levels; a stump on it is memorisation",
    "merchant_id": "identifier with thousands of levels; a stump on it is memorisation",
    "terminal_id": "identifier; probed instead through its null pattern",
    "device_id": "identifier; reuse across customers is an aggregate feature, not a column",
    "ip": "identifier; prefix sharing is an aggregate feature, not a column",
    "ag_agent_id": "identifier; agent fan-out is an aggregate feature, not a column",
    "ag_kya_token": "credential string; probed instead through kya_registered",
    "ag_mandate_id": "identifier, unique per mandate",
    "ag_mandate_hash": "digest; replay detection is a cross-row join, not a column",
    "ag_mandate_issued_ts": "probed as mandate age relative to the event",
    "ts": "probed as epoch, hour of day and day of week",
    "original_event_id": "identifier; probed instead through its null pattern",
    "dispute_raised_ts": "post-hoc, and probed as a lag; see POST_HOC_COLUMNS",
    **{c: "ground truth; HARD RULE 1" for c in LABEL_COLUMNS},
    **{
        c: "resolves weeks after authorisation; using it would be temporal leakage"
        for c in POST_HOC_COLUMNS
    },
}

#: Columns whose null pattern is itself worth probing. ``original_event_id`` is
#: here because an *orphan* credit -- money going out with no purchase behind it
#: -- is the F1-03 signal, and the probe has to be able to see it.
_NULLITY_COLUMNS: Final[tuple[str, ...]] = (
    "terminal_id",
    "device_id",
    "ip",
    "lat",
    "ag_agent_id",
    "original_event_id",
    "settlement_lag_hours",
)

#: List-valued columns, probed by length.
_LIST_COLUMNS: Final[tuple[str, ...]] = (
    "ag_scope_categories",
    "ag_scope_allowed_merchants",
    "ag_provenance_chain",
    "ag_ingested_content_ids",
)

#: Tri-state booleans carried as objects: ``None`` off the agentic rail.
_TRISTATE_COLUMNS: Final[tuple[str, ...]] = (
    "ag_kya_registered",
    "ag_human_present",
    "ag_consent_sig_valid",
)

#: Maximum distinct levels before a categorical is dropped as an identifier.
_MAX_LEVELS: Final[int] = 32

#: Sentinel for missing numerics. Far below any real value, so a stump can split
#: on "is missing" and we can see it doing so.
_MISSING: Final[float] = -1.0e12


def build_probe_matrix(frame: pd.DataFrame) -> pd.DataFrame:
    """Explode a transaction frame into the single columns a stump may split on.

    Every output column is something an issuer could read off one authorisation
    message. Nothing here is a cross-row aggregate: this probe exists to prove
    that per-row evidence is *insufficient*.
    """
    out: dict[str, np.ndarray] = {}

    ts = frame["ts"]
    out["ts_epoch"] = ts.astype("int64").to_numpy() / 1e9
    out["ts_hour"] = ts.dt.hour.to_numpy().astype(float)
    out["ts_dow"] = ts.dt.dayofweek.to_numpy().astype(float)
    mandate_age = (ts - frame["ag_mandate_issued_ts"]).dt.total_seconds()
    out["mandate_age_seconds"] = mandate_age.fillna(_MISSING).to_numpy()

    for column in frame.columns:
        if column in EXCLUDED_COLUMNS or column in _LIST_COLUMNS:
            continue
        series = frame[column]
        if column in _TRISTATE_COLUMNS:
            out[column] = series.map({True: 1.0, False: 0.0}).fillna(_MISSING).to_numpy(dtype=float)
            continue
        if pd.api.types.is_numeric_dtype(series) and not pd.api.types.is_bool_dtype(series):
            out[column] = series.fillna(_MISSING).to_numpy(dtype=float)
            continue
        if pd.api.types.is_bool_dtype(series):
            out[column] = series.to_numpy(dtype=float)
            continue
        levels = series.dropna().unique()
        if len(levels) > _MAX_LEVELS:
            continue
        as_string = series.astype("string")
        for level in sorted(map(str, levels)):
            # ``fillna(False)`` matters: on a nullable string column the
            # comparison yields pd.NA off the agentic rail, and a NaN in the
            # probe matrix would silently drop the feature instead of measuring
            # it. Absent means "not this level", which is what we want to probe.
            out[f"{column}={level}"] = as_string.eq(level).fillna(False).to_numpy(dtype=float)

    for column in _LIST_COLUMNS:
        lengths = frame[column].map(lambda v: float(len(v)) if v is not None else np.nan)
        out[f"{column}_len"] = lengths.fillna(_MISSING).to_numpy(dtype=float)

    for column in _NULLITY_COLUMNS:
        out[f"{column}_isnull"] = frame[column].isna().to_numpy(dtype=float)

    return pd.DataFrame(out, index=frame.index)


def _fold(auc: float) -> tuple[float, str]:
    """Collapse a signed AUC to (magnitude, direction).

    ``hi`` means the attack sits **high** on this feature relative to the
    comparison population; ``lo`` means it sits low. Keeping the direction is
    what stops a reader inferring the sign of a feature from its name.
    """
    return (auc, "hi") if auc >= 0.5 else (1.0 - auc, "lo")


def _stump_auc(x: np.ndarray, y: np.ndarray) -> tuple[float, str]:
    """The stronger of a gini-optimal depth-1 stump and the column's rank AUC.

    Returns the magnitude **and** which way the attack sits. See the module
    docstring: the magnitude on its own is direction-blind, and a
    direction-blind table is how ``auth_response=approved`` gets misread as
    "approved more often" when it means the reverse.
    """
    from sklearn.metrics import roc_auc_score
    from sklearn.tree import DecisionTreeClassifier

    if np.unique(x).size < 2:
        return 0.5, "hi"
    rank_value, rank_direction = _fold(float(roc_auc_score(y, x)))

    stump = DecisionTreeClassifier(max_depth=1, random_state=0)
    stump.fit(x.reshape(-1, 1), y)
    fitted_value, fitted_direction = _fold(
        float(roc_auc_score(y, stump.predict_proba(x.reshape(-1, 1))[:, 1]))
    )
    if fitted_value > rank_value:
        return fitted_value, fitted_direction
    return rank_value, rank_direction


def probe_attack(
    background: pd.DataFrame,
    attack: pd.DataFrame,
    *,
    max_negatives: int | None = 60_000,
    seed: int = 1337,
) -> pd.DataFrame:
    """Rank every single feature by how well it separates ``attack`` from clean.

    Args:
        background: The clean population.
        attack: One injector's labelled rows.
        max_negatives: Subsample the background to this many rows. AUC is a rank
            statistic and does not depend on the class ratio, so this changes the
            runtime and not the answer. ``None`` uses every row.
        seed: Subsampling seed.

    Returns:
        A frame of ``feature`` / ``auc`` / ``direction``, sorted worst-first
        (most separating). ``direction`` is ``hi`` when the attack sits high on
        the feature and ``lo`` when it sits low.
    """
    negatives = background
    if max_negatives is not None and len(background) > max_negatives:
        negatives = background.sample(n=max_negatives, random_state=seed)

    combined = pd.concat([negatives, attack], ignore_index=True)
    labels = np.r_[np.zeros(len(negatives)), np.ones(len(attack))]
    matrix = build_probe_matrix(combined)

    scores = [(name, *_stump_auc(matrix[name].to_numpy(), labels)) for name in matrix.columns]
    return (
        pd.DataFrame(scores, columns=["feature", "auc", "direction"])
        .sort_values("auc", ascending=False)
        .reset_index(drop=True)
    )


def probe_report(
    background: pd.DataFrame,
    attacks: dict[str, pd.DataFrame],
    *,
    max_negatives: int | None = 60_000,
    top_k: int = 3,
    slices: dict[str, np.ndarray] | None = None,
) -> pd.DataFrame:
    """Best-single-feature AUC per attack, plus the runners-up.

    The combined ``ALL`` row is measured against every attack row at once, which
    is the number that matters for the dataset as a whole.

    Args:
        background: The clean population.
        attacks: ``card_id -> attack frame``.
        max_negatives: Background subsample size; AUC is rank-based.
        top_k: How many runners-up to record.
        slices: ``card_id -> boolean mask over ``background``` naming the
            definitional slice that attack should be measured inside. Built from
            :meth:`BaseAttack.probe_slice`; see the module docstring for why the
            gate then applies to the conditional number.
    """
    rows: list[dict[str, object]] = []
    slices = slices or {}
    everything = pd.concat(list(attacks.values()), ignore_index=True)

    for card_id, frame in [*attacks.items(), ("ALL", everything)]:
        ranked = probe_attack(background, frame, max_negatives=max_negatives)
        best = ranked.iloc[0]

        slice_auc: float | None = None
        slice_feature: str | None = None
        slice_direction: str | None = None
        slice_n: int | None = None
        mask = slices.get(card_id)
        if mask is not None and bool(mask.any()):
            negatives = background[mask]
            slice_n = len(negatives)
            sliced = probe_attack(negatives, frame, max_negatives=max_negatives)
            slice_auc = float(sliced.iloc[0]["auc"])
            slice_feature = str(sliced.iloc[0]["feature"])
            slice_direction = str(sliced.iloc[0]["direction"])

        # The gate applies to the conditional number when one exists.
        gated = best["auc"] if slice_auc is None else slice_auc
        rows.append(
            {
                "attack_id": card_id,
                "n_events": len(frame),
                "best_feature": str(best["feature"]),
                "best_auc": float(best["auc"]),
                "best_direction": str(best["direction"]),
                "slice_auc": slice_auc,
                "slice_feature": slice_feature,
                "slice_direction": slice_direction,
                "slice_n": slice_n,
                "runners_up": ", ".join(
                    f"{r.feature} {r.auc:.3f} {r.direction}"
                    for r in ranked.iloc[1 : 1 + top_k].itertuples()
                ),
                "passes": bool(gated <= GATE_AUC),
            }
        )
    return pd.DataFrame(rows)


def build_slices(background: pd.DataFrame, registry: dict[str, type]) -> dict[str, np.ndarray]:
    """Ask every injector for its definitional slice over ``background``."""
    out: dict[str, np.ndarray] = {}
    for card_id, cls in registry.items():
        mask = cls.probe_slice(background)
        if mask is not None:
            out[card_id] = np.asarray(mask, dtype=bool)
    return out


def format_probe_table(report: pd.DataFrame) -> str:
    """Render the probe report as the block the foundry CLI prints."""
    has_slice = "slice_auc" in report.columns and report["slice_auc"].notna().any()

    def _named(feature: object, direction: object, width: int) -> str:
        """``feature [hi]`` / ``feature [lo]`` -- never the bare magnitude."""
        if not isinstance(feature, str):
            return "-".ljust(width)
        tag = f" [{direction}]" if isinstance(direction, str) else ""
        return f"{feature[: width - len(tag)]}{tag}".ljust(width)

    lines = [
        f"best-single-feature AUC  (depth-1 stump on every column; gate <= {GATE_AUC:.2f})",
        "",
        f"  {'attack':<8} {'events':>7} {'vs all':>7}  {'feature [hi/lo]':<34} "
        f"{'in slice':>8} {'slice n':>9}  {'feature (within slice)':<34} ok",
        f"  {'-' * 8} {'-' * 7} {'-' * 7}  {'-' * 34} {'-' * 8} {'-' * 9}  {'-' * 34} --",
    ]
    for row in report.itertuples():
        flag = "ok" if row.passes else "!!"
        slice_auc = getattr(row, "slice_auc", None)
        slice_n = getattr(row, "slice_n", None)
        cell = "       -" if slice_auc is None or pd.isna(slice_auc) else f"{slice_auc:>8.3f}"
        if slice_n is None or pd.isna(slice_n):
            n_cell = "        -"
        else:
            thin = "!" if int(slice_n) < THIN_SLICE_ROWS else " "
            n_cell = f"{int(slice_n):>8,}{thin}"
        best_cell = _named(row.best_feature, getattr(row, "best_direction", None), 34)
        slice_cell = _named(
            getattr(row, "slice_feature", None), getattr(row, "slice_direction", None), 34
        )
        lines.append(
            f"  {row.attack_id:<8} {row.n_events:>7,} {row.best_auc:>7.3f}  "
            f"{best_cell} {cell} {n_cell}  {slice_cell} {flag}"
        )
    lines.append("")
    lines.append(
        "  [hi] = the attack sits HIGH on that feature; [lo] = it sits LOW. The AUC\n"
        "  magnitude alone is direction-blind (the probe reports max(a, 1-a)), and\n"
        "  reading it without the tag is how 'auth_response=approved 0.69' gets\n"
        "  mistaken for 'approved more often' when it means the opposite."
    )
    lines.append("")
    lines.append("  runners-up (next strongest single columns):")
    for row in report.itertuples():
        lines.append(f"    {row.attack_id:<8} {row.runners_up}")
    lines.append("")
    lines.append(
        "  A depth-1 stump is the weakest possible model. Nothing here clears the gate,\n"
        "  so every attack requires combined evidence -- which is what the firewall is."
    )
    if has_slice:
        lines.append("")
        lines.append(
            "  'in slice' measures the attack inside the definitional slice of traffic it\n"
            "  lives in -- agent-mediated authorisations for the F1 cards, and refunds by\n"
            "  agent-mediated customers for F1-03. Unconditionally, ANY attack carrying an\n"
            "  agentic block scores ~0.92 on the nullity of any ag_ column, and any refund\n"
            "  attack ~0.99 on txn_type, because those columns are the attack's definition\n"
            "  rather than evidence of it. THE GATE APPLIES TO THE SLICE COLUMN where one\n"
            "  exists; the unconditional number is printed so the change of denominator is\n"
            "  visible, and 'slice n' prints the size of that denominator; a '!' marks a\n"
            f"  slice thinner than {THIN_SLICE_ROWS:,} rows, where it is fragile\n"
            "  number and should be quoted with the denominator attached. Each injector\n"
            "  declares its own slice in probe_slice(); tests/test_probe_slices.py proves\n"
            "  mechanically that a slice reads ONLY columns a detector knows before it\n"
            "  scores, and none that are a consequence of the attack."
        )
    return "\n".join(lines)


def main() -> None:
    """Probe every injector against a small background. Run: ``python -m ...probe``."""
    from mantis.foundry.base.reference import load_reference_stats
    from mantis.foundry.base.simulator import SimulationConfig, simulate_frame
    from mantis.foundry.injectors import REGISTRY
    from mantis.foundry.injectors.base import PopulationView, run_injector

    cfg = SimulationConfig(n_events=40_000, seed=7, n_customers=1_500, n_merchants=4_000)
    background = simulate_frame(cfg, load_reference_stats())
    view = PopulationView.build(background)
    attacks = {
        card_id: run_injector(cls, view, seed=7) for card_id, cls in sorted(REGISTRY.items())
    }
    slices = build_slices(background, dict(REGISTRY))
    print(format_probe_table(probe_report(background, attacks, slices=slices)))


if __name__ == "__main__":
    main()
