"""The real transaction panel the scorecard measures against.

    python -m mantis.foundry.fidelity.real        # what is present, and its shape

The file is the Kaggle ``kartik2112/fraud-detection`` (Sparkov) CSV pair, pulled
by ``scripts/fetch_reference.py`` into ``data/reference/``. It is **not
committed** — half a gigabyte, and HARD RULE 4 says a clean clone must run with
no Kaggle token. So every entry point here degrades: ``available()`` is false, the
scorecard prints the sections it can still compute, and says in its own output
which ones it could not.

What this data is, stated before any number is quoted
-----------------------------------------------------
Sparkov is a **US** card panel: 1.3 million authorisations over 537 days, 983
cardholders, 693 merchants, 14 spend categories, USD, 0.58% fraud. It is itself
synthetic — generated by Brandon Harris's Sparkov simulator and widely used as a
fraud-modelling benchmark. Calling it "real" is therefore a claim about its
**role**, not its provenance: it is data this project did not author, produced by
a generator this project has never seen, and it is the only external reference
available for a rail that has no public panel at all.

That is a weaker claim than "measured against production card traffic", and the
scorecard says so on its face rather than letting a reader assume otherwise.

What transfers, and what emphatically does not
-----------------------------------------------
``scripts/fit_reference.py`` already drew this line for calibration, and the
scorecard draws the same one for measurement. A US panel in dollars cannot be
compared to an Indian population in rupees on **absolute** amount, on category
mix, on geography, on BIN, on 3-D Secure, or on channel — and it has no agentic
rail at all, because no such panel exists. Comparing those would produce a large
number that measures the difference between two countries.

What compares is **shape**: the diurnal curve, the day-of-week curve, the
dispersion of spend within a category, the rank-frequency structure of an
acceptance estate, and how often a cardholder transacts. Those are dimensionless
or scale-free, and they are what :mod:`mantis.foundry.fidelity.common` builds.
"""

from __future__ import annotations

import sys
from pathlib import Path
from typing import Final

import numpy as np
import pandas as pd

from mantis.core.paths import REFERENCE_DIR

__all__ = [
    "REAL_FILES",
    "RealPanel",
    "available",
    "load_real",
    "missing_message",
]

#: The two CSVs the Kaggle archive contains, in the order they are concatenated.
#: ``fraudTrain`` is the first ~18 months and ``fraudTest`` the remainder; they
#: are one continuous panel that Kaggle happens to ship pre-split.
REAL_FILES: Final[tuple[str, ...]] = ("fraudTrain.csv", "fraudTest.csv")

#: Only these columns are read. The panel carries names, street addresses, jobs
#: and dates of birth; none of it is needed to compare a diurnal curve, so none
#: of it is loaded into memory or into any artefact this repo writes.
_USE_COLUMNS: Final[list[str]] = [
    "trans_date_trans_time",
    "cc_num",
    "merchant",
    "category",
    "amt",
    "is_fraud",
]


class RealPanel:
    """A loaded reference panel plus the provenance line that must accompany it."""

    __slots__ = ("frame", "n_source_rows", "sampled", "source")

    def __init__(
        self, frame: pd.DataFrame, source: list[str], n_source_rows: int, sampled: bool
    ) -> None:
        self.frame = frame
        self.source = source
        self.n_source_rows = n_source_rows
        self.sampled = sampled

    @property
    def provenance(self) -> str:
        files = ", ".join(self.source)
        note = (
            f"Kaggle kartik2112/fraud-detection (Sparkov): {files}. "
            f"{self.n_source_rows:,} rows"
        )
        if self.sampled:
            first, last = self.frame["ts"].min().date(), self.frame["ts"].max().date()
            note += f", cut to {len(self.frame):,} over {first}..{last}"
        return note + ". US panel, USD, itself synthetic - see mantis/foundry/fidelity/real.py."

    def __len__(self) -> int:
        return len(self.frame)


def paths() -> list[Path]:
    """The reference CSVs that are actually on disk, in panel order."""
    return [REFERENCE_DIR / name for name in REAL_FILES if (REFERENCE_DIR / name).is_file()]


def available() -> bool:
    """True when at least one half of the panel is present."""
    return bool(paths())


def missing_message() -> str:
    """What to tell a reader when the panel is absent. Not an error — a state."""
    return (
        "No reference panel in data/reference/. The scorecard's KS, JS, TSTR and "
        "discriminator sections need one.\n"
        "  Fetch it:  python scripts/fetch_reference.py\n"
        "  (~210 MB, no Kaggle token needed, never committed - see HARD RULE 4.)"
    )


def load_real(days: int | None = 90, seed: int = 1337) -> RealPanel:
    """Load the panel, cut to a contiguous window of ``days``.

    **A row sample would be wrong here, and getting this wrong is silent.** Half
    the shape space is velocity: transactions in the trailing hour, in the
    trailing day, seconds since this cardholder's previous transaction. Dropping
    nine rows in ten deflates every one of them by roughly a factor of ten, and
    the scorecard would then report a large, confident, entirely manufactured
    difference in cardholder behaviour. The first version of this loader did
    exactly that.

    A contiguous window keeps each retained cardholder's history intact and makes
    the two panels comparable on the one axis that matters for a rate: they cover
    the same number of days. The synthetic population spans 89, so the default is
    90. The window is placed by ``seed`` rather than taken from the head of the
    file, because the panel spans two calendar years and its first months have a
    different seasonal composition from its whole.

    ``days=None`` loads everything, which is what the module's own CLI prints.

    Raises ``FileNotFoundError`` with :func:`missing_message` when nothing is
    there, because a scorecard that silently reported on a phantom reference
    would be worse than one that reported nothing.
    """
    found = paths()
    if not found:
        raise FileNotFoundError(missing_message())

    frames = [pd.read_csv(path, usecols=_USE_COLUMNS) for path in found]
    raw = pd.concat(frames, ignore_index=True)
    n_source = len(raw)

    frame = pd.DataFrame(
        {
            "ts": pd.to_datetime(raw["trans_date_trans_time"]),
            "amount": raw["amt"].astype(float),
            "category": raw["category"].astype(str),
            # The card number is the only cardholder key the panel has. It is
            # hashed to a short opaque id here so that no PAN-shaped string
            # reaches a feature matrix, a figure or a committed artefact -- the
            # identity of a cardholder is irrelevant to every metric below, only
            # the grouping is needed.
            "customer_id": _opaque(raw["cc_num"], "cus"),
            "merchant_id": _opaque(raw["merchant"], "mer"),
            "is_fraud": raw["is_fraud"].astype(bool),
        }
    )

    frame = frame.sort_values("ts", kind="mergesort").reset_index(drop=True)

    sampled = False
    if days is not None:
        first, last = frame["ts"].min(), frame["ts"].max()
        span = (last - first).days
        if span > days:
            offset = int(np.random.default_rng(seed).integers(0, span - days + 1))
            start = first + pd.Timedelta(days=offset)
            stop = start + pd.Timedelta(days=days)
            frame = frame.loc[(frame["ts"] >= start) & (frame["ts"] < stop)]
            frame = frame.reset_index(drop=True)
            sampled = True

    return RealPanel(frame, [p.name for p in found], n_source, sampled)


def _opaque(values: pd.Series, prefix: str) -> pd.Series:
    """Stable short ids for a key column, without carrying the key itself."""
    codes = pd.factorize(values.astype(str))[0]
    return pd.Series([f"{prefix}-{c:06d}" for c in codes], index=values.index)


def main() -> int:
    """Print what is on disk. Run: ``python -m mantis.foundry.fidelity.real``."""
    print("MANTIS reference panel")
    print()
    if not available():
        print(missing_message())
        return 1

    panel = load_real(days=None)
    frame = panel.frame
    span = (frame["ts"].max() - frame["ts"].min()).days
    print(f"  {panel.provenance}")
    print()
    print(f"  rows          {len(frame):,}")
    first, last = frame["ts"].min().date(), frame["ts"].max().date()
    print(f"  span          {first} to {last}  ({span} days)")
    print(f"  cardholders   {frame['customer_id'].nunique():,}")
    print(f"  merchants     {frame['merchant_id'].nunique():,}")
    print(f"  categories    {frame['category'].nunique()}")
    print(f"  fraud         {frame['is_fraud'].mean():.4%}")
    print(f"  amount median {frame['amount'].median():.2f} USD")
    print(
        f"  velocity      {len(frame) / frame['customer_id'].nunique() / max(span, 1):.3f} "
        "txn per cardholder per day"
    )
    print()
    print("  Compared on shape only: hour curve, day-of-week curve, within-category")
    print("  amount dispersion, merchant rank-frequency, cardholder velocity. Absolute")
    print("  amount, category mix, geography, BIN, 3DS and channel are NOT compared -")
    print("  see this module's docstring for why.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
